# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: day18
version: '0.0.0'
github: "Strikingwolf/day18"
license: MIT
author: "Strikingwolf"
maintainer: "Strikingwolf"
# synopsis: A new Haskeleton package.
# description: day18 is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - attoparsec
  - free
  - mtl
  - ListZipper
  - text
  source-dirs: library
  default-extensions: 
    - FlexibleContexts
    - FlexibleInstances
    - MultiParamTypeClasses
    - DeriveFunctor

executables:
  day18:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - day18
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N