# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: day5
version: '0.0.0'
github: "Strikingwolf/day5"
license: MIT
author: "Faye"
maintainer: "Faye"
# synopsis: A new Haskeleton package.
# description: day5 is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall
default-extensions:
  - MultiParamTypeClasses
  - FunctionalDependencies
  - FlexibleInstances
  - FlexibleContexts

library:
  dependencies:
  - base
  - lens
  - mtl
  - ListZipper
  source-dirs: library

executables:
  day5:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - day5
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -O2